///////////////////////////////////////////////////////////
//  CardValue.cs
//  Implementation of the Class CardValue
//  Generated by Enterprise Architect
//  Created on:      16-дек-2020 9:55:06
//  Original author: local-adm-sabitovka
///////////////////////////////////////////////////////////




namespace enums {
	/// <summary>
	/// Значения карт
	/// </summary>
	public enum CardValue : int {

		Zero,
		One,
		Two,
		Three,
		Four,
		Five,
		Six,
		Seven,
		Eight,
		Nine,
		Reverse,
		Skip,
		DrawTwo,
		DrawFour,
		Wild

	}//end CardValue

}//end namespace enums