///////////////////////////////////////////////////////////
//  CardDeck.cs
//  Implementation of the Class CardDeck
//  Generated by Enterprise Architect
//  Created on:      16-дек-2020 9:54:47
//  Original author: local-adm-sabitovka
///////////////////////////////////////////////////////////




/// <summary>
/// Колода карт
/// </summary>
public class CardDeck {
	public List<Card> Cards{
		//read property
		get{;}
		//write property
		set{;}
	}


	public List<Card> Cards{
		//read property
		get{;}
		//write property
		set{;}
	}



	~CardDeck(){

	}

	public virtual void Dispose(){

	}

	public CardDeck(){

	}

	/// 
	/// <param name="cards"></param>
	public CardDeck(List<Card> cards){

	}

	/// 
	/// <param name="count"></param>
	public List<Card> Draw(int count){

		return null;
	}

	public Card First(){

		return null;
	}

	/// <summary>
	/// Перетасовует колоду карт
	/// </summary>
	public void Shuffle(){

	}

}//end CardDeck