///////////////////////////////////////////////////////////
//  CardColor.cs
//  Implementation of the Class CardColor
//  Generated by Enterprise Architect
//  Created on:      16-дек-2020 9:59:17
//  Original author: adm-sabitovka
///////////////////////////////////////////////////////////




namespace enums {
	/// <summary>
	/// Цвета карт
	/// </summary>
	public enum CardColor : int {

		Red,
		Green,
		Blue,
		Yellow,
		Wild

	}//end CardColor

}//end namespace enums