///////////////////////////////////////////////////////////
//  Game.cs
//  Implementation of the Class Game
//  Generated by Enterprise Architect
//  Created on:      16-дек-2020 9:58:51
//  Original author: adm-sabitovka
///////////////////////////////////////////////////////////


using System.Collections.Generic;
using UNOServer.ServerObjects;

namespace UNOServer.GameObjects {

	/// <summary>
	/// Контроллер игры
	/// </summary>
	public class Game {

		ServerObject server;

		/// <summary>
		/// Колода карт
		/// </summary>
		public CardDeck DeckCards { get; set;}

		/// <summary>
		/// Список игроков
		/// </summary>
		public List<Player> Players { get; set; }

		/// <summary>
		/// Колода сброса
		/// </summary>
		public List<Card> ThrowCards { get;  set; }

		/// 
		/// <param name="numberOfPlayers"></param>
		public Game(List<Player> players, ServerObject server) {
			Players = players;
			this.server = server;
			DeckCards = new CardDeck();
			ThrowCards = new List<Card>();

            for (int i = 0; i < players.Count; i++) {
				Players[i].Position = i;
            }

			players.ForEach(System.Console.WriteLine);

			server.TargetMessage("1233", players[0]);
		}

		/// 
		/// <param name="turn"></param>
		private void AddToDiscardPile(PlayerTurn turn) {

		}

		public void PlayGame() {
            System.Console.WriteLine("Играем в игрушечку");
		}

	}//end Game

}