///////////////////////////////////////////////////////////
//  Handler.cs
//  Implementation of the Class Handler
//  Generated by Enterprise Architect
//  Created on:      16-дек-2020 9:54:48
//  Original author: adm-sabitovka
///////////////////////////////////////////////////////////


namespace UNOServer.GameObjects {

	/// <summary>
	/// Граничащий класс для взаимодействия с пользователем и контроллером игры.
	/// </summary>
	public class Handler {

		private Game game;
		public Game m_Game;

		public Handler() {

		}

		~Handler() {

		}

		public virtual void Dispose() {

		}

		/// 
		/// <param name="card"></param>
		public void displayWrongCard(Card card) {

		}

		/// 
		/// <param name="index"></param>
		public void playCard(int index) {

		}

		public void requestColor() {

		}

		public void Start() {

		}

	}//end Handler

}