///////////////////////////////////////////////////////////
//  PlayerTurn.cs
//  Implementation of the Class PlayerTurn
//  Generated by Enterprise Architect
//  Created on:      16-дек-2020 9:54:49
//  Original author: adm-sabitovka
///////////////////////////////////////////////////////////


namespace UNOServer.GameObjects {

	/// <summary>
	/// Класс, в котором будет хрнится предудщий ход.
	/// </summary>
	public class PlayerTurn {

		public Card Card { get; set; }
		/// <summary>
		/// Используеся в основном для "Диких" карт
		/// </summary>
		public CardColor DeclaredColor { get; set; }
		public TurnResult Result { get; set; }

	}//end PlayerTurn

}