///////////////////////////////////////////////////////////
//  TurnResult.cs
//  Implementation of the Class TurnResult
//  Generated by Enterprise Architect
//  Created on:      16-дек-2020 9:55:07
//  Original author: adm-sabitovka
///////////////////////////////////////////////////////////




namespace enums {
	/// <summary>
	/// Хранит все возможные ситуации, которые возникают после завершения игроком хода
	/// </summary>
	public enum TurnResult : int {

		/// <summary>
		/// Начало игры
		/// </summary>
		GameStart,
		/// <summary>
		/// Игрок разыграл обычную карту с цифрой
		/// </summary>
		PlayedCard,
		/// <summary>
		/// Разыграна карта пропустить ход
		/// </summary>
		Skip,
		/// <summary>
		/// Разыграна карта взять две
		/// </summary>
		DrawTwo,
		/// <summary>
		/// Игрок вынужден вытащить карту
		/// </summary>
		Attacked,
		/// <summary>
		/// Игрок вынужден вытянуть карту, потому что у него нет подходящей
		/// </summary>
		ForceDraw,
		/// <summary>
		/// Игрок вынужден взять карту потому что у него нет подходящей карты, но вытянутую
		/// карту можно разыграть
		/// </summary>
		ForceDrawPLay,
		/// <summary>
		/// Обычная дикая карта
		/// </summary>
		WildCard,
		/// <summary>
		/// Разыграна дика карта "Возьми 4"
		/// </summary>
		WildDarwFour,
		/// <summary>
		/// Разыграна карта смены направления
		/// </summary>
		Reversed

	}//end TurnResult

}//end namespace enums