///////////////////////////////////////////////////////////
//  Card.cs
//  Implementation of the Class Card
//  Generated by Enterprise Architect
//  Created on:      16-дек-2020 9:58:29
//  Original author: adm-sabitovka
///////////////////////////////////////////////////////////




using enums;
/// <summary>
/// Класс карты
/// </summary>
public class Card {

	private CardColor color;
	private CardValue value;

	public Card(){

	}

	~Card(){

	}

	public virtual void Dispose(){

	}

}//end Card