///////////////////////////////////////////////////////////
//  Game.cs
//  Implementation of the Class Game
//  Generated by Enterprise Architect
//  Created on:      16-дек-2020 9:58:51
//  Original author: adm-sabitovka
///////////////////////////////////////////////////////////




/// <summary>
/// Контроллер игры
/// </summary>
public class Game {

	/// <summary>
	/// Колода карт
	/// </summary>
	public CardDeck deckCards{
		//read property
		get{;}
		//write property
		set{;}
	}
	/// <summary>
	/// Список игроков
	/// </summary>
	public List<Player> Players{
		//read property
		get{;}
		//write property
		set{;}
	}
	/// <summary>
	/// Колода сброса
	/// </summary>
	public List<Card> ThrowCards{
		//read property
		get{;}
		//write property
		set{;}
	}
	public Player m_Player;
	public Handler m_Handler;
	public CardDeck m_CardDeck;

	public Game(){

	}

	~Game(){

	}

	public virtual void Dispose(){

	}

	/// 
	/// <param name="numberOfPlayers"></param>
	public Game(int numberOfPlayers){

	}

	/// 
	/// <param name="turn"></param>
	private void AddToDiscardPile(PlayerTurn turn){

	}

	private void nextPlayer(){

	}

	public void PlayGame(){

	}

}//end Game