///////////////////////////////////////////////////////////
//  PlayerTurn.cs
//  Implementation of the Class PlayerTurn
//  Generated by Enterprise Architect
//  Created on:      16-дек-2020 9:54:49
//  Original author: adm-sabitovka
///////////////////////////////////////////////////////////




using enums;
/// <summary>
/// Класс, в котором будет хрнится предудщий ход.
/// </summary>
public class PlayerTurn {
	public Card Card{
		//read property
		get{;}
		//write property
		set{;}
	}
	/// <summary>
	/// Используеся в основном для "Диких" карт
	/// </summary>
	public CardColor DeclaredColor{
		//read property
		get{;}
		//write property
		set{;}
	}
	public TurnResult Result{
		//read property
		get{;}
		//write property
		set{;}
	}


	public Card Card{
		//read property
		get{;}
		//write property
		set{;}
	}
	/// <summary>
	/// Используеся в основном для "Диких" карт
	/// </summary>
	public CardColor DeclaredColor{
		//read property
		get{;}
		//write property
		set{;}
	}
	public TurnResult Result{
		//read property
		get{;}
		//write property
		set{;}
	}

	public PlayerTurn(){

	}

	~PlayerTurn(){

	}

	public virtual void Dispose(){

	}

}//end PlayerTurn